const factions = [
    {name: "Valarjar", text: "Pround warrior who died during battle and where taken to the Asgard by the valkyr. They now serve Odin's for the enternity.", alignement: "lawfull good", slug: "valarjar"},
    {name: "Helarjar", text: "Imbued in anti-magie they serve Hella in the death for ever.", alignement: "lawfull evil", slug: "helarjar"},
    {name: "Elves Kingdom", text: "A noble race that live in peace in the forest, They prefere to stay away from the chaos of the world.", alignement: "lawfull neutral", slug: "elves-kingdom"},
    {name: "Ninjas", text: "Trained by master Wu, they are the protector of Ninjago.", alignement: "lawfull neutral", slug: "ninjas"},
    {name: "The imperium", text: "A hight tech empire that seek to enslave the dragon and harness theire power.", alignement: "lawfull evil", slug: "the-imperium"},
    {name: "Swamp Tribe", text: "A powerfull tribe of human warrior who revert the serpentine. They pocesses weapon inbued in deadly poison They live in swamp.", alignement: "chaotic neutral", slug: "swamp-tribe"},
    {name: "The Guild", text: "An organisation that regroup adventurers from all over the world. They help people in exchange for a reward. They follow the law.", alignement: "lawfull neutral", slug: "adventurers"},
    {name: "Mercenarys", text: "An organisation formed by a man ban from the guild. The have no ethic and will do anything for the correct reward.", alignement: "neutral neutral", slug: "mercenarys"},
    {name: "Sky Pirates", text: "A group of pirate who have fund weapon alling them to master wind.", alignement: "chaotic neutral", slug: "sky-pirates"},
    {name: "Nexo-knights Kingdom", text: "Kingdom where a talented ", alignement: "lawfull neutral", slug: "nexo-knights-kingdom"},
    {name: "Squeletons", text: "Raised by a powerfull witch that wanted to overcome death. Only magic can defeat them.", alignement: "neutral evil", slug: "squeletons"},
    {name: "Dwarves Kingdom", text: "The best blacksmith in the universe. They live in giant city under montaigne.", alignement: "lawfull neutral", slug: "dwarves-kingdom"},
    {name: "Space", text: "Ninjago city space agency. They send satelite, make scientific research and have an advenced base on Mars.", alignement: "lawfull neutral", slug: "space"},
    {name: "Heros of Ninjago", text: "Created by Dr.Doom, this assosiation regroupe people with special abilities and protec ninjago city and it's citizen.", alignement: "lawfull good", slug: "heros-of-ninjago"},
    {name: "Ghost", text: "A group of Ghost at the order of Morrow.", alignement: "neutral evil", slug: "ghost"},
    {name: "Swarms", text: "An innsectoid alien species. They multiply quickly and submerge every thing. They seek galactic domination.", alignement: "chaotic evil", slug: "swarms"},
    {name: "Martians", text: "An alien species that live on Mars. They are a peacefull species that seek to understand the universe.", alignement: "lawfull neutral", slug: "martians"},
    {name: "Brainiacs", text: "Super inteligent alien species. They posses advenced thecnology and seek galactic domonation.", alignement: "neutral evil", slug: "brainiacs"},
    {name: "Lion Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi. The Lion in charge of the sacred pond and give a just amounch of Chi to each tribe. They are noble and loyal.", alignement: "lawfull neutral", slug: "lion-tribe"},
    {name: "Crocodile Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "chaotic neutral", slug: "crocodile-tribe"},
    {name: "Eagle Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "lawfull neutral", slug: "eagle-tribe"},
    {name: "Wolve Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "chaotic neutral", slug: "wolve-tribe"},
    {name: "Gorilla Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "chaotic neutral", slug: "gorilla-tribe"},
    {name: "Bear Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "neutral good", slug: "bear-tribe"},
    {name: "Raven Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "neutral evil", slug: "raven-tribe"},
    {name: "Snake Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "chaotic neutral", slug: "snake-tribe"},
    {name: "Sea Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "chaotic neutral", slug: "sea-tribe"},
    {name: "Insectoid Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "chaotic neutral", slug: "insectoid-tribe"},
    {name: "Pheonix Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "lawfull good", slug: "pheonix-tribe"},
    {name: "Tiger Tribe" ,text:"An animal tribe that ganed enligtment after drink pure Chi.", alignement: "chaotic neutral", slug: "tiger-tribe"},
    {name: "Polar-Bear Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "neutral evil", slug: "polar-bear-tribe"},
    {name: "SaberTooth Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "neutral evil", slug: "sabertooth-tribe"},
    {name: "Vulture Tribe", text: "An animal tribe that ganed enligtment after drink pure Chi.", alignement: "neutral evil", slug: "vulture-tribe"},
    {name: "Island Ruler", text: "lorem ipsum dolor sit amet", alignement: "chaotic evil", slug: "island-ruler"},
    {name: "Jedi Temple", text: "lorem ipsum dolor sit amet", alignement: "lawfull good", slug: "jedi-temple"},
    {name: "Sith Congregation", text: "lorem ipsum dolor sit amet", alignement: "chaotic evil", slug: "sith-congregation"},
    {name: "Mandalorian Tribe", text: "lorem ipsum dolor sit amet", alignement: "true neutral", slug: "mandalorian-tribe"},
    {name: "The Horde", text: "Multiple tribe of monster have regrouped to form a horde.", alignement: "chaotic evil", slug: "the-horde"},
    {name: "The Infernos", text: "A group of monster who obey the Enchantresse, a powerfull sorceress.", alignement: "chaotic evil", slug: "the-infernos"},
    {name: "The destruction", text: "Those who serve Siegfried, the avatar of destruction. Theire only goal is to destroy everything that existe down to the last atom.", alignement: "chaotic evil", slug: "the-destruction"}
];

const realms = [
    {name:"Origine's realm", size:"Major", description:"The first realm and the bigest. It served as the base realm during the Great Merge.", slug:"origine-realm"},
    {name:"Asgard", size:"Minor", description:"Realm created by Odin when he assended to Godhood.", slug:"asgard"},
    {name:"Helheim", size:"Minor", description:"Realm created by Hella when she assended to Godhood.", slug:"helheim"},
    {name: "The Imperium", size:"Medium", description:"A hight tech realm. They aim to enslave the dragon and harness theire power. It was merger to the origine realm during the Great Merge.", slug:"the-imperium"},
    {name: "The Underworld", size:"Medium", description:"A realm of darkness and death. It was merged to the origine realm during the Great Merge.", slug:"the-underworld"},
    {name: "The cloud kingdom", size:"Minor", description:"A realm of eternal light. It was merged to the origine realm during the Great Merge.", slug:"the-cloud-kingdom"},
    {name: "Wyldness", size:"Medium", description:"A land free of humanity. It contain one of the rarest resource : the Chi. It was merged to the origine realm during the Great Merge.", slug:"wyldness"},
];

const worlds = [
    {name:"Alfeim", realm:"Origine's realm", system:"Bc-586", nbStars:"1", description:"Composed of three continents separated by vast sea it's home to multiple civilisation.", slug:"alfeim"},
    {name:"Ruin's of TeamGuard", realm:"Origine's realm", system:"Bc-586", nbStars:"1", description:"After the betraille of Bellion, the plannet was first vitrified. Then a couple years after an explosion of unkown origine destroid it.", slug:"ruin-of-teamgard"},
    {name: "Mandalore", realm:"Origine's realm", system:"système Mandalore", nbStars:"2", description:"A desertic plannet with multiple tribe of warrior who never remove their helmet.", slug:"mandalore"},
    {name: "Korriban", realm:"Origine's realm", system:"système Mandalore", nbStars:"2", description:"A plannet of dark side, a place of pelgrimage for the sith.", slug:"korriban"},
    {name: "Corusant", realm:"Origine's realm", system:"Argon", nbStars:"1", description:"The capital of the galactic federation and a city planet. It also accommodate the Jedi temple.", slug:"corusant"},
    {name: "Earth", realm:"Origine's realm", system:"Sol", nbStars:"1", description:"The cradle of humanity.", slug:"earth"},
    {name: "Mars", realm:"Origine's realm", system:"Sol", nbStars:"1", description:"The red plannet.", slug:"mars"},
    {name: "Niflheim", realm:"Wyldness", system:"none", nbStars:"0", description:"Now a world of ice and permanent night, it was once a world full of life. The Chi originate from this place, and created antropomarphique animals.", slug:"niflheim"},
    {name: "Asgard", realm:"Asgard", system:"none", nbStars:"1", description:"Only world of it's realm, it's not a planet but a fragment of one that separed it self from the planet during the treachery of Hela.", slug:"asgard"},
    {name: "Helheim", realm:"Helheim", system:"none", nbStars:"0", description:"Only world of it's realm. A planet with a hole the size of a continent, it was once an eden. Now it's only a dead world.", slug:"helheim"},
    {name: "Musphelheim", realm:"Origine's realm", system:"Cf-864", nbStars:"10", description:"A world of fire and lava, no life can survive there.", slug:"musphelheim"},
    {name: "Tenut", realm:"Origine's realm", system:"Jx-843", nbStars:"2", description:"Planets of origine of the Brainiacs, the planet died long ago as they harvested everything in theire systeme from the planets to the star.", slug:"tenut"},
    {name: "Mentu", realm:"Origine's realm", system:"Jx-843", nbStars:"2", description:"Planets of origine of the Swarm, they quickly moved away after the death of there system, starting to colonize systeme after system.", slug:"mentu"},
];

const continents = [
    {name: "Nidavelir", world: "Alfeim", realm:"Origine's realm", description:"Mountaigne chaine", slug:"nidavelir"},
    {name: "Vanaheim", world: "Alfeim", realm:"Origine's realm", description:"Primordial forest", slug:"vanaheim"},
    {name: "Midgard", world: "Alfeim", realm:"Origine's realm", description:"forest and plain", slug:"midgard"},
    {name: "Ninjago", world: "Earth", realm:"Origine's realm", description:"The first half of the pangea. It was separated by the first spinzutsu master.", slug:"ninjago"},
    {name: "Dark Island", world: "Earth", realm:"Origine's realm", description:"The second half of the pangea. It was separated by the first spinzutsu master.", slug:"dark-island"},
];

const citys = [
    {name:"Erebor", continents: "Nidavelir", world:"Alfeim", realm: "Origine's realm", description:"Capital of the Dwarf Kingdom", slug:"erebor"},
    {name:"Tendrasyl", continents: "Vanaheim", world:"Alfeim", realm: "Origine's realm", description:"Capital of the Elven Kingdom", slug:"tendrasyl"},
    {name:"Duranmoran", continents: "Midgard", world:"Alfeim", realm: "Origine's realm", description:"Head quarter of the adventurer guild", slug:"duranmoran"},
    {name:"Camelot", continents: "Midgard", world:"Alfeim", realm: "Origine's realm", description:"New capital of the Nexo-Kinght Kingdom", slug:"camelot"},
    {name:"Ninjago City", continents: "Ninjago", world:"Earth", realm: "Origine's realm", description:"Capital of Ninjago", slug:"ninjago-city"},
    {name:"Stiix", continents: "Ninjago", world:"Earth", realm: "Origine's realm", description:"City of the swamp tribe", slug:"stiix"},
    {name: "Ever lasting city", continents:"none", world:"Niflheim", realm:"Origine's realm", description:"Home to the saber tooth, the vultur's, the polar bear and the frost samourai's. It's made of ever lasting ice.", slug:"ever-lasting-city"},
    {name: "Asgard", continents:"none", world:"Asgard", realm:"Asgard", description:"Last city of a dead world. Made of pure gold, it's home to Odin and his valarjar.", slug:"asgard"},
    {name: "Skyr", continents:"none", world:"Helheim", realm:"Helheim", description:"A bastion made of a black and green rock swelling anti-magic. It's the pallace of Hela.", slug:"skyr"},
    {name: "The living castle", continents:"none", world:"Musphelheim", realm:"Origine's realm", description:"A living castle made by the enchanteress, she can move it anywhere.", slug:"the-living-castle"},
    {name: "Dalaran", continents:"none", world:"none", realm:"Origine's realm", description:"The city of the mages, floating in the infinity of space.", slug:"dalaran"},
    {name: "Temut"}
];

const artifacts = [
    {name: "Shield of Nyx", divinity: "Nyx", power: "Indestrutible shield, that can absorb any attack.", slug: "shield-of-nyx", status: "Held by La Créatrice", "autority": 7},
    {name: "On/Off Staff", divinity: "La Créatrice", power: "Allow to turn any reliques on or off.", slug: "on-off-staff", status: "Held by La Créatrice", "autority": 5},
    {name: "The Hammer of Creation", divinity: "La Créatrice", power: "Allow to create anything.", slug: "the-hammer-of-creation", status: "Held by La Créatrice", "autority": 6},
    {name: "Tridents of Poseidon", divinity: "Poseidon", power: "Allow to controlle sea creature and manipulate water.", slug: "tridents-of-poseidon", status: "Held by Nia", "autority": 5},
    {name: "Gaya's apple", divinity: "Gaya", power: "Create a circle (20m radius). Inside the cicle every wound is instantly heal and it's impossible to died.", slug: "gayas-apple", status: "Held by Odin", "autority": 5},
    {name: "Gungnir", divinity: "Odin", power: "The spear never miss it's target and always return to it's bearer.", slug: "gungnir", status: "Held by Odin", "autority": 6},
    {name: "Balmung", divinity: "Siegfried", power: "The sword can cut through and destroy anything.", slug: "balmung", status: "Held by Odin", "autority": 6},
    {name: "Key of the primordial sea", divinity: "Tiamat", power: "Create an impenetrable temple of water. Only the bearer can decide who can enter. It heal the bearer and his allies.", slug: "key-of-the-primordial-sea", status: "Held by Odin", "autority": 7},
    {name: "Enuma Elish", divinity: "Marduk", power: "A spear capable to fire a beam of pure destruction capable of tearing space and time.", slug: "enuma-elish", status: "Held by Odin", "autority": 7},
    {name: "The Eye of Horus", divinity: "Horus", power: "Allow to see find anything.", slug: "the-eye-of-horus", status: "Held by Odin", "autority": 6},
    {name: "The Gem of Hermes", divinity: "Hermes", power: "Allow to travel anywhere.", slug: "the-gem-of-hermes", status: "Held by Odin", "autority": 3},
    {name: "The sword of Amaterasu", divinity: "Amaterasu", power: "The sword can cut through anything and can create a blinding light. It allow it's user to becaume ligth and use powerfull ligth based attack.", slug: "the-sword-of-amaterasu", status: "Held by Odin", "autority": 5},
    {name: "The cristal of Tartarus", divinity: "hades", power: "Allow to create a portal to Tartarus.", slug: "the-cristal-of-tartarus", status: "Held by Odin", "autority": 5},
    {name: "Zeus's thunder", divinity: "Zeus", power: "Allow to control thunder and lightning.", slug: "zeus-thunder", status: "Held by Odin", "autority": 6},
    {name: "Isis's wings", divinity: "Isis", power: "Allow to fly, manipulate wind and heal.", slug: "isis-wings", status: "Held by the dwarves king", "autority": 5},
    {name: "The Behemoth's horn", divinity: "Behemoth", power: "A spear forged with the horn of the Behemoth. It can create a shockwave capable of destroying anything, the user can manipulate earth and magma.", slug: "the-behemoths-horn", status: "Held by Cole", "autority": 3},
    {name: "Divine Axe Rita", divinity: "Rita", power: "An axe capable of absorbing heat. I great it's bearer immense power that increase as the sun rise. The user can also create small sun.", slug: "divine-axe-rita", status: "Held by Ecanor", "autority": 3},
    {name: "The Book of Horus", divinity: "Horus", power: "Allow to see the future.", slug: "the-eye-of-horus", status: "Held by Ivan", "autority": 6},
    {name: "The sword of Mars", divinity: "Mars", power: "Inflict wound that can never be heal.", slug: "the-sword-of-mars", status: "Held by Gengis", "autority": 4},
    {name: "The armor of Baldr", divinity: "Baldr", power: "Once put, only the bearer can remove it. Make it's bearer invulnerable to everything expete one thing.", slug: "the-armor-of-baldr", status: "Held by Bjorn", "autority": 4},
    {name: "Susanoo's sword", divinity: "Susanoo", power: "The sword allow it's owner to use thunder based attack, create a thunder shield to protect himself and to fly.", slug: "susanoo-sword", status: "Held by first spinjitzu master", "autority": 5},
    {name: "The Staff of Anubis", divinity: "Anubis", power: "Allow to control the dead, travel to anywhere, communicate with the dead and guide the soul of the dead.", slug: "the-staff-of-anubis", status: "Held by Anubis", "autority": 6},
    {name: "Atlas masse", divinity: "Atlas", power: "Indestrutible masse that grant it's user incredible strenght.", slug: "atlas-masse", status: "Held by Jay", "autority": 3},
    {name: "Souls blade", divinity: "Unknown", power: "The sword can absorb the soul of it's victim. The user can use the soul to increase his power.", slug: "souls-blade", status: "Held by White", "autority": 8},
];
